name: dynstat
on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  dynstat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build
        uses: calamity-inc/dynstat@senpai

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5

        with:
          branch: gh-pages
          folder: build
